name: f8x
on:
  push:
    paths:
    - 'f8x'

jobs:
  ubuntu-latest-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: init
        run:
          touch /tmp/IS_CI

      - name: Run
        run:
          sudo bash f8x

      - name: Run -h
        run:
          sudo bash f8x -h

      - name: Run -clear
        run:
          sudo bash f8x -clear

      - name: Run -b
        run:
          sudo bash f8x -b

      - name: Run -d
        run:
          sudo bash f8x -d

      - name: Run -s
        run:
          sudo bash f8x -s

      - name: Run -f
        run:
          sudo bash f8x -f

      - name: Run -k
        run:
          sudo bash f8x -k

      - name: Run -info
        run:
          sudo bash f8x -info

      - name: log
        run:
          cat /tmp/f8x_error.log

  ubuntu-latest-build2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: init
        run:
          touch /tmp/IS_CI

      - name: Run
        run:
          sudo bash f8x

      - name: Run -all
        run:
          sudo bash f8x -all

      - name: log
        run:
          cat /tmp/f8x_error.log

  ubuntu-latest-build3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: init
        run:
          touch /tmp/IS_CI

      - name: Run
        run:
          sudo bash f8x

      - name: Run -docker
        run:
          sudo bash f8x -docker

      - name: Run -lua
        run:
          sudo bash f8x -lua

      - name: Run -nn
        run:
          sudo bash f8x -nn

      - name: Run -go
        run:
          sudo bash f8x -go

      - name: Run -code
        run:
          sudo bash f8x -code

      - name: log
        run:
          cat /tmp/f8x_error.log

  ubuntu-latest-build4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: init
        run:
          touch /tmp/IS_CI

      - name: Run
        run:
          sudo bash f8x

      - name: Run -py3
        run:
          sudo bash f8x -py3

      - name: Run -py37
        run:
          sudo bash f8x -py37

      - name: Run -py38
        run:
          sudo bash f8x -py38

      - name: Run -py39
        run:
          sudo bash f8x -py39

      - name: Run -py2
        run:
          sudo bash f8x -py2

      - name: log
        run:
          cat /tmp/f8x_error.log

  ubuntu-latest-build5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: init
        run:
          touch /tmp/IS_CI

      - name: Run
        run:
          sudo bash f8x

      - name: Run -phantomjs
        run:
          sudo bash f8x -phantomjs

      - name: Run -vol
        run:
          sudo bash f8x -vol

      - name: Run -vol3
        run:
          sudo bash f8x -vol3

      - name: Run -yakit
        run:
          sudo bash f8x -yakit

      - name: log
        run:
          cat /tmp/f8x_error.log
